### ISSUE TITLE
[2pt] Setup Kanban Board

### ISSUE THREAD

**Issue by TheLuisAbarca** [TheLuisAbarca/RecipeApp_RoR#2]
We are a group of two people:
- @TheLuisAbarca 
- @gemmen29

and this is the project [link](https://github.com/TheLuisAbarca/RecipeApp_RoR/projects/1)

**Comment by BrianSammit** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello @gemmen29  and @TheLuisAbarca , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job setting up the Kanban board 
- you split the work fairly 
- Great job creating de card properly 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![Well-Done-Applause](https://user-images.githubusercontent.com/64173189/162787926-48702f35-f4c4-40fa-a1eb-06678277ef02.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
